# Website specifications
title: Carlos Kayser
description: "Python, Big Data, Cloud & Edge Computing, and more."

author: Carlos Kayser
email: carloshkayser@gmail.com
avatar: "https://avatars.githubusercontent.com/u/17982392?v=4"
round-avatar: true
twitter_username: carloshkayser_
github_username:  carloshkayser

url: "https://carloshkayser.github.io" # Website's base hostname and protocol (e.g.: http://example.com)
baseurl: "/" # Website's subpath (e.g.: /blog)

# Website collections
# collections_dir: collections
# collections:
#     news:
#     keynote_speakers:
#         sort_by: order

# Website SASS settings
sass:
    sass_dir: _sass
    style: compressed

# Jekyll plugins
plugins:
    - jekyll-seo-tag
    # - jekyll-feed
    # - jekyll-remote-theme
    # - jekyll-include-cache