# Website's base hostname and protocol (e.g.: http://example.com)
url: "https://carloshkayser.github.io"

# Website's subpath (e.g.: /blog)
baseurl: "/"

# Website specifications
title: Carlos Kayser
description: "Python, Big Data, Cloud & Edge Computing, and more."

locale: en_US

author: Carlos Kayser
social:
  name: Carlos Kayser
  links:
    - https://github.com/carloshkayser
    - https://linkedin.com.br/in/carloshkayser

# google_site_verification: 

# Website collections
# collections_dir: collections
# collections:
#     news:
#     keynote_speakers:
#         sort_by: order

# Website SASS settings
sass:
  sass_dir: _sass
  style: compressed



# Jekyll plugins
plugins:
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
  # - jekyll-feed
  # - jekyll-remote-theme
  # - jekyll-include-cache
